default: &default
  enhance_image_tag: true
  static_image_support: true
  cdn_subdomain: true
  secure_distribution: false
  private_cdn: false
  cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %> 
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %> 
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>

development:
  <<: *default

test:
  <<: *default
