development:
  adapter: postgresql
  encoding: utf8
  database: bartr_development
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: bartr_test
  username: postgres
  password: postgres
  host: localhost

# overriden by heroku automatically
production:
  adapter: postgresql
  encoding: utf8
  database: bartr_production
  username: postgres
  password: postgres
  host: localhost